"""
Convert the human leakage audit into RENUMBERING-PROOF links. One-off; run where the audit ran.

Why. configs/eval_exclude.yaml first listed test design_ids. Design ids are assigned by
enumerating connected components, so one borderline geometric match that flips between OpenCV
builds renumbers designs and can reshuffle the whole split (D-45). An exclusion list keyed by
design_id silently points at the wrong designs on another machine.

What it writes. Each audited leak becomes a LINK between two images, keyed by image_id (the
stable SHA1 of the relative path, identical on every machine, and free of Drive filenames, so
the file is safe to commit):

  test_image_id   an image of the design that was in TEST when audited
  other_image_id  the TRAIN image judged to be the same saree, or a real colourway twin

evaluate.py resolves links against whatever manifest it is given, and excludes a test design
only when its partner is in TRAIN there. It also stores every audited test image_id, so the
evaluation can report how much of the current test set the human audit actually covered.

Sources: the local manifest (numbering the audit used), outputs/leakage_audit.csv (nearest train
image per test image) and outputs/real_colourway_pairs.csv (accepted colourway twins).

Run:  python scripts/make_exclusion_links.py
"""

from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd
import yaml

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from src.data.adapters import stable_image_id  # noqa: E402

KIND = {  # from the audit notes in the old yaml
    **{d: "same_saree" for d in [
        "drive_d00030", "drive_d00045", "drive_d00039", "drive_d00003", "drive_d00034",
        "drive_d00033", "drive_d00037", "drive_d00007", "drive_d00005", "drive_d00078",
        "drive_d00028", "drive_d00041", "drive_d00067", "drive_d00087", "drive_d00036",
        "drive_d00061", "drive_d00020", "drive_d00016", "drive_d00055"]},
    **{d: "colourway_twin" for d in [
        "kaggle_d00166", "kaggle_d00206", "kaggle_d00259", "kaggle_d00298", "kaggle_d00083",
        "kaggle_d00086"]},
    **{d: "colourway_twin_uncertain" for d in ["kaggle_d00223", "kaggle_d00160"]},
}


def main() -> int:
    old = yaml.safe_load(Path("configs/eval_exclude.yaml").read_text(encoding="utf-8"))
    old_ids = old.get("exclude_test_designs") or []
    assert set(old_ids) == set(KIND), "old yaml and audit notes disagree; refusing to guess"

    man = pd.read_csv("outputs/manifest.csv", keep_default_na=False)
    real = man[man.is_synthetic.astype(str) == "False"]
    gal = real[real.role == "gallery"].set_index("design_id")
    audit = pd.read_csv("outputs/leakage_audit.csv")
    cw = pd.read_csv("outputs/real_colourway_pairs.csv")
    cw = cw[cw.decision == "accept"]
    by_path = real.set_index("path")

    links, rows = [], []
    for d in old_ids:
        test_path = gal.loc[d, "path"]
        other_path, how = None, ""
        if KIND[d].startswith("colourway"):
            hit = cw[(cw.design_a == d) | (cw.design_b == d)]
            for r in hit.itertuples():
                cand = r.path_b if r.design_a == d else r.path_a
                if by_path.loc[cand, "split"] == "train":
                    other_path, how = cand, "accepted colourway pair"
                    break
        if other_path is None:
            a = audit[audit.test_design == d].sort_values("cosine", ascending=False)
            if len(a):
                other_path, how = a.iloc[0].nearest_train_path, f"nearest train, cos {a.iloc[0].cosine:.3f}"
        assert other_path is not None, f"no partner found for {d}"
        links.append({"test_image_id": stable_image_id(test_path),
                      "other_image_id": stable_image_id(other_path),
                      "kind": KIND[d], "audit_numbering": d})
        rows.append((d, KIND[d], stable_image_id(test_path), stable_image_id(other_path),
                     by_path.loc[other_path, "design_id"], how))

    # Only TEST galleries were audited; val galleries were never reviewed.
    audited = sorted(stable_image_id(p) for p in gal[gal.split == "test"].path)
    out = {
        "version": 2,
        "keyed_by": "image_id (stable SHA1 of the relative path; never renumbered)",
        "links": links,
        "audited_test_image_ids": audited,
    }
    header = (
        "# Post-hoc leakage exclusion, version 2: LINKS keyed by image_id, not design_id.\n"
        "# Design ids are renumbered when a borderline geometric match flips between machines\n"
        "# (DECISIONS.md D-45), so an id-keyed list breaks; image_id is a stable hash of the path.\n"
        "# evaluate.py excludes a TEST design when its linked partner is in TRAIN in the manifest\n"
        "# being evaluated, and reports how much of that test set the human audit covered.\n"
        "# Generated by scripts/make_exclusion_links.py from the 2026-10-02 visual audit.\n")
    Path("configs/eval_exclude.yaml").write_text(
        header + yaml.safe_dump(out, sort_keys=False, width=100), encoding="utf-8")

    print(f"{'audit id':14s} {'kind':26s} {'test image_id':17s} {'partner image_id':17s} partner (audit numbering)")
    for r in rows:
        print(f"{r[0]:14s} {r[1]:26s} {r[2]:17s} {r[3]:17s} {r[4]}  [{r[5]}]")
    print(f"\n{len(links)} links written; {len(audited)} audited test images recorded")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
